language: node_js
services:
  - docker

before_install:
  - docker pull node:18
  - docker run -d -v $(pwd):/app -w /app node:18 /bin/sh -c "while :; do sleep 1; done"

install:
  - docker exec $(docker ps -q) npm install -g pnpm
  - docker exec $(docker ps -q) pnpm install

before_script:
  - docker exec $(docker ps -q) pnpm prisma generate
  - docker exec $(docker ps -q) pnpm prisma db push

script:
  - docker exec $(docker ps -q) pnpm build

deploy:
  provider: script
  script: docker exec $(docker ps -q) pnpm run deploy
  on:
    branch: main

env:
  global:
    - DATABASE_URL="mongodb+srv://ahmed78:GP9qOLtDU8fijZW5@nextjs-todo.zhatip1.mongodb.net/todo"
    - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_YnJhdmUtbGVvcGFyZC0xOS5jbGVyay5hY2NvdW50cy5kZXYk
    - CLERK_SECRET_KEY=sk_test_ZSrsEAk6BERQhjAPAe6gB2eCNJigwtBw8wX8N5FjLn
    - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
    - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up